### ISSUE TITLE
Set full Height & Width on Html & Body Tag in style.css

### ISSUE THREAD

**Issue by KrshnK** [Muskan7576/E-commerce#1]
# Issue: Set Full Height & Width on HTML & Body Tags

## Description
the HTML and Body tags in the style.css file lack the necessary styles to ensure full height and width.

## Expected Behavior
This issue aims to address this by implementing the appropriate CSS properties.

## Current Code
Include the relevant code snippets from your `style.css` file where you attempt to set the full height and width on HTML and Body tags.

```css
/*your CSS code here */
```

## Proposed Changes
Provide the modified code or changes you suggest to resolve the issue.

```css
/* Add your modified CSS code here */
html, body {
  height: 100%;
  width: 100%;
  /* Any additional styles */
}
```

### Browser Information:
- **Browser:** [e.g., Chrome, Firefox, Safari]
- **Version:** [e.g., 94.0.4606.81]

### Development Environment:
- **Operating System:** [e.g., Windows 10, macOS, Linux]
- **IDE/Code Editor:** [e.g., Visual Studio Code, Sublime Text]

## Checklist
- [x] I have tested these changes locally.
- [x] I have checked for any console errors.
- [x] I have included all relevant information.
